import type { Metadata } from "next";
import "./globals.css";
import Header from "./site-header";

// Fonts are defined via local @font-face in globals.css to avoid network fetches during build.

export const metadata: Metadata = {
  title: "Course Browser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
